- name: Display container details
  community.docker.docker_container_info:
    name: "{{ item.name }}"
  with_items: "{{ docker_containers }}"
  register: container_info_results

- name: Print container details
  debug:
    var: container_info_results.results
