- name: Deploy containers
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: started
    networks:
      - name: swarm_overlay
    ports: "{{ item.ports }}"
    env: "{{ item.environment | default({}) }}"
  with_items: "{{ docker_containers | default([]) }}"