all:
  hosts:
    web01:
      ansible_host: 172.31.22.148
    app01:
      ansible_host: 172.31.18.81
    db01:
      ansible_host: 172.31.20.183
    
  children:
    webservers:
      hosts:
        web01:
    appservers:
      hosts:
        app01:
    dbservers:
      hosts:
        db01:

    us_east_1:
      children:
        webservers:
        appservers:
        dbservers:

      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: default.pem
        #ansible_python_interpreter: /usr/bin/python3