all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 172.31.32.243
    appservers:
      hosts:
        app01:
          ansible_host: 172.31.47.36
    dbservers:
      hosts:
        db01:
          ansible_host: 172.31.32.174

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: default.pem
    ansible_python_interpreter: /usr/bin/python3