all:
  hosts:
    web01:
      ansible_host: 172.31.93.177
    web02:
      ansible_host: 172.31.80.119
    db01:
      ansible_host: 172.31.80.204
    
  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
    us_east_1:
      children:
        webservers:
        dbservers:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: default.pem