- name: Create Swarm overlay network
  command: docker network create --driver overlay --attachable "{{ swarm_network_name }}"
  args:
    creates: "/var/lib/docker/network/files/{{ swarm_network_name }}"
  register: swarm_network_creation
  when: inventory_hostname == groups['webservers'][0]
  changed_when: "'{{ swarm_network_name }}' not in swarm_network_creation.stdout"