- name: Create Docker Swarm overlay network
  ansible.builtin.command:
    cmd: docker network create \
         --driver overlay \
         --attachable \
         vprofile_network
  become: true
  ignore_errors: true
  register: create_network

- name: Debug network creation
  debug:
    var: create_network.stdout