- name: Install MySQL server
  yum:
    name: mysql-server
    state: present

- name: Start and enable MySQL service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Ensure MySQL Python libraries are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-PyMySQL

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present