- name: Deploy Docker containers
  tasks:
    - name: Start containers based on group vars
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        ports: "{{ item.ports }}"
        volumes: "{{ item.volumes | default([]) }}"
        env: "{{ item.environment | default({}) }}"
      with_items: "{{ docker_containers | default([]) }}"