- name: Create Docker Compose file
  copy:
    dest: /home/{{ ansible_user }}/docker-compose.yml
    content: |
      version: '3.8'
      services:
        {% for container in docker_containers %}
        {{ container.name }}:
          image: {{ container.image }}
          ports:
          {% for port in container.ports %}
            - "{{ port }}"
          {% endfor %}
          volumes:
          {% for volume in container.volumes %}
            - "{{ volume }}"
          {% endfor %}
          restart: always
        {% endfor %}
  when: docker_containers is defined