- name: Deploy Docker containers on group-specific hosts
  hosts: all
  tasks:
    - name: Start Docker containers for each group
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        ports: "{{ item.ports }}"
        volumes: "{{ item.volumes | default([]) }}"
        env: "{{ item.environment | default({}) }}"
      with_items: "{{ docker_containers }}"
      when: docker_containers is defined