- name: Create Docker Compose file
  template:
    src: docker-compose.j2
    dest: /home/{{ ansible_user }}/docker-compose.yml
  when: docker_containers is defined and docker_containers | length > 0

- name: Start containers using Docker Compose
  command: >
    {{ 'docker compose' if 'Docker Compose version v2' in compose_version.stdout else 'docker-compose' }} up -d
  args:
    chdir: /home/{{ ansible_user }}
  when: docker_containers is defined and docker_containers | length > 0