- name: Install Docker
  package:
    name: docker
    state: present

- name: Install prerequisites for Docker Compose
  package:
    name: python3-pip
    state: present

- name: Install Docker Compose via pip
  pip:
    name: docker-compose

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true