- name: Install required packages for Docker
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker repository
  command:
    cmd: >
      yum-config-manager --add-repo
      https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  package:
    name: docker-ce
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Install Docker Compose (V2)
  shell: |
    if ! command -v docker compose > /dev/null 2>&1; then
      yum install -y docker-ce-plugin-docker-compose;
    fi
  args:
    executable: /bin/bash
- name: Check Docker Compose version

  shell: |
    if command -v docker compose > /dev/null 2>&1; then
      docker compose version;
    elif command -v docker-compose > /dev/null 2>&1; then
      docker-compose --version;
    else
      exit 1;
    fi
  register: compose_version
  failed_when: compose_version.rc != 0
- debug:
    var: compose_version.stdout