- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Deploy index.html
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
