docker_containers:
  - name: vprofiledb
    image: mikolajwiduch/vprofiledb
    ports:
      - "3306:3306"
    volumes:
      - "/data/vprofiledb:/db"
    environment:
      MYSQL_DATABASE: "accounts"
      MYSQL_ROOT_PASSWORD: "vprodbpass"